
services:
  database:
    image: ${DB_IMAGE}
    environment:
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}"
    volumes:
      - db_data:/var/lib/${DB_IMAGE}:${DB_NAME}/data

  dockeep:
    build: .
    ports:
      - "${APP_PORT}:8080"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DRIVER: ${DB_DRIVER}
      DB_MAX_POOL_SIZE: ${DB_MAX_POOL_SIZE}
      DB_MIN_IDLE_CONNECTIONS: ${DB_MIN_IDLE_CONNECTIONS}
      DB_IDLE_TIMEOUT_MS: ${DB_IDLE_TIMEOUT_MS}
      DB_MAX_LIFETIME_MS: ${DB_MAX_LIFETIME_MS}
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_BUCKET_NAME: ${AWS_BUCKET_NAME}

    depends_on:
      - database