spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  output:
    ansi:
      enabled: ALWAYS
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  application:
    name: dockeep
  jackson:
    deserialization:
      fail-on-unknown-properties: true

management:
  endpoints:
    web:
      base-path: /dockeep-actuator
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

aws:
  region: ${AWS_REGION}
  bucket:
    name: ${AWS_BUCKET_NAME}
  credentials:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}

#KAFKA_BOOTSTRAP_SERVERS:

#REDIS_HOST:
#REDIS_PORT:

#kafka:
#  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}