spring:
  output:
    ansi:
      enabled: ALWAYS
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  application:
    name: dockeep
  jackson:
    deserialization:
      fail-on-unknown-properties: true

management:
  endpoints:
    web:
      base-path: /dockeep-actuator
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

aws:
  region: ${AWS_REGION}
  bucket:
    name: ${AWS_BUCKET_NAME}

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

REDIS_HOST:
REDIS_PORT: