cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION}
    bucket:
      name: ${AWS_BUCKET_NAME}

messaging:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

cache:
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

db:
  jdbc-url: ${DB_URL}
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}
  driver: ${DB_DRIVER}
  max-pool-size: ${DB_MAX_POOL_SIZE}
  min-idle-connections: ${DB_MIN_IDLE_CONNECTIONS}
  idle-timeout-ms: ${DB_IDLE_TIMEOUT_MS}
  max-lifetime-ms: ${DB_MAX_LIFETIME_MS}

spring:
  profiles:
    active: prod