cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION}
    bucket:
      name: ${AWS_BUCKET_NAME}

messaging:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}