on:
  push:
    branches: ["main", "master", "development"]
  workflow_dispatch:

jobs:
  build-test-create-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven


      - name: Configure Maven for GitHub packages
        run: |
          mkdir -p ~/.m2
          cat <<EOF > ~/.m2/settings.xml
          <settings>
            <servers>
              <server>
                <id>github</id>
                <username>${{ secrets.REPO_USERNAME }}</username>
                <password>${{ secrets.REPO_TOKEN }}</password>
              </server>
            </servers>
          </settings>
          EOF
        shell: bash

      - name: Build and test
        run: mvn clean verify -B
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
          REPO_USERNAME: ${{ secrets.REPO_USERNAME }}


      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/authmat
          tags: |
            type=ref,event=branch
            type=ref,event=tag   
            type=sha             


      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            REPO_USERNAME=${{ secrets.REPO_USERNAME }}
            REPO_TOKEN=${{ secrets.REPO_TOKEN }}